stages:
  - test
  - build

test-unit:
  stage: test
  image: registry.naspersclassifieds.com/library/docker/build-images/python:3.7
  script:
    - make test

test-style:
  stage: test
  image: registry.naspersclassifieds.com/library/docker/build-images/python:3.7
  script:
    - make format-check

build-wheel:
  stage: build
  image: registry.naspersclassifieds.com/library/docker/build-images/python:3.7
  script:
    - make build
