stages:
  - build
  - test

default:
  image: registry.naspersclassifieds.com/library/docker/build-images/python:3.7

build-wheel:
  stage: build
  script:
    - make build

build-venv:
  stage: build
  script:
    - make venv
  artifacts:
    paths:
      - .venv

test-unit:
  stage: test
  dependencies:
    - build-venv
  script:
    - make test

test-lint:
  stage: test
  dependencies:
    - build-venv
  script:
    - make lint

test-style:
  stage: test
  dependencies:
    - build-venv
  script:
    - make format-check
