stages:
  - build
  - test
  - publish

default:
  image: ${IMAGE_CICD_DEFAULT}

build-wheel:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - dist

build-venv:
  stage: build
  script:
    - make venv
  artifacts:
    paths:
      - .venv

test-unit:
  stage: test
  dependencies:
    - build-venv
  script:
    - make test

test-lint:
  stage: test
  dependencies:
    - build-venv
  script:
    - make lint

test-style:
  stage: test
  dependencies:
    - build-venv
  script:
    - make format-check

publish-gitlab-pypi:
  stage: publish
  dependencies:
    - build-wheel
  before_script:
    - pip install twine
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - master
  when: manual
